### ISSUE TITLE
关于StringRequest中的加载进度监听LoadingListener

### ISSUE THREAD

**Issue by imyyq-star** [bacy/volley#2]
此接口中的onLoading方法的参数long count 和 long current似乎不正确，我去访问www.baidu.com，onLoading方法只被响应了一次，count和current的值相等，请问这是正确的吗

**Comment by bacy** [comment]
onLoading一般只用在文件上传和大文件下载中。从socket建立之后开始，每100ms刷新一次，并不是接收一个字节触发一次。

**Comment by imyyq-star** [comment]
多谢回复，我明白了！
